version: '2.0'

services:
  mongo:
    image: andresvidal/rpi3-mongodb3
    ports:
      - 27017:27017
      - 27018:27018
    volumes:
      - /data/db:/data/db
      - /data/configdb:/data/configdb
    command: bash -c "rm -f /data/db/mongod.lock && mongod --journal"
    restart: always
  pool:
    image: rhbroberg/pool-controller-arm:latest
    ports:
      - 8080:8080
    restart: always
    devices:
    - "/dev/ttyUSB0:/dev/ttyUSB0"
