version: '3.1'

services:
  mongo:
    image: rhbroberg/mongo-multi:latest
    ports:
      - 27017:27017
    restart: always
  pool:
    image: rhbroberg/pool-controller-multi:latest
    ports:
      - 8080:8080
    restart: always
