version: '2.0'

services:
  nginx-proxy:
    image: rhbroberg/nginx-proxy
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /path/to/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      options:
        max-size: "4m"
        max-file: "10"

  nginx-letsencrypt:
    image: rhbroberg/docker-letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /path/to/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      options:
        max-size: "2m"
        max-file: "10"

  pool:
    image: httpd:2.4
    restart: always
    environment:
      - VIRTUAL_HOST=pool.mystic.onthegrid.net
      - LETSENCRYPT_HOST=pool.mystic.onthegrid.net
      - LETSENCRYPT_EMAIL=rhbroberg@yahoo.com
      - NODE_ENV=docker-test
#    expose:
#      - "80"
#    devices:
#    - "/dev/ttyUSB0:/dev/ttyUSB0"

